/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package RegisterUser;

import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.*;

import java.io.*;
import java.net.*;

/**
 *
 * @author asus
 */
public class RegisterForm extends javax.swing.JFrame {

    /**
     * Creates new form Registration
     */
    public RegisterForm() {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jCalendar1 = new com.toedter.calendar.JCalendar();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        date = new javax.swing.JLabel();
        email = new javax.swing.JLabel();
        stname = new javax.swing.JLabel();
        lastname = new javax.swing.JLabel();
        pnumber = new javax.swing.JLabel();
        lname = new javax.swing.JTextField();
        fname = new javax.swing.JTextField();
        number = new javax.swing.JTextField();
        mail = new javax.swing.JTextField();
        uname = new javax.swing.JLabel();
        password = new javax.swing.JLabel();
        pword = new javax.swing.JPasswordField();
        user = new javax.swing.JTextField();
        submit = new javax.swing.JButton();
        clear = new javax.swing.JButton();
        password2 = new javax.swing.JLabel();
        pword2 = new javax.swing.JPasswordField();
        exit = new javax.swing.JButton();
        msg = new javax.swing.JLabel();
        terms = new javax.swing.JCheckBox();
        date_chooser = new com.toedter.calendar.JDateChooser();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Registration ");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(99, 99, 99)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 317,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(334, Short.MAX_VALUE)));
        jPanel1Layout.setVerticalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(15, 15, 15)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 41,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(14, Short.MAX_VALUE)));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 750, 70));

        date.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        date.setText("Date of Birth:");
        getContentPane().add(date, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, 120, 20));

        email.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        email.setText("E-mail:");
        getContentPane().add(email, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 60, 20));

        stname.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        stname.setText("First Name:");
        getContentPane().add(stname, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, 100, 20));

        lastname.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lastname.setText("Last Name:");
        getContentPane().add(lastname, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, 90, 20));

        pnumber.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        pnumber.setText("Phone Number:");
        getContentPane().add(pnumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, 130, 20));
        getContentPane().add(lname, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 150, 160, -1));

        fname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fnameActionPerformed(evt);
            }
        });
        fname.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                fnameKeyReleased(evt);
            }
        });
        getContentPane().add(fname, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 120, 160, -1));

        number.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numberActionPerformed(evt);
            }
        });
        getContentPane().add(number, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 180, 160, -1));

        mail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mailActionPerformed(evt);
            }
        });
        mail.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                mailKeyReleased(evt);
            }
        });
        getContentPane().add(mail, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 90, 160, -1));

        uname.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        uname.setText("User Name:");
        getContentPane().add(uname, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, 110, 20));

        password.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        password.setText("Password:");
        getContentPane().add(password, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 270, 110, 20));
        getContentPane().add(pword, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 270, 160, -1));
        getContentPane().add(user, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 240, 160, -1));

        submit.setText("Submit");
        submit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                submitMouseClicked(evt);
            }
        });
        submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitActionPerformed(evt);
            }
        });
        getContentPane().add(submit, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 380, 80, 30));

        clear.setText("Clear");
        clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearActionPerformed(evt);
            }
        });
        getContentPane().add(clear, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 380, 90, 30));

        password2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        password2.setText("Confirm Password:");
        getContentPane().add(password2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 300, 170, 20));
        getContentPane().add(pword2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 300, 160, -1));

        exit.setText("Exit");
        getContentPane().add(exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 380, 90, 30));
        getContentPane().add(msg, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 430, 310, 20));

        terms.setText("Accept terms and conditions");
        getContentPane().add(terms, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 340, -1, -1));
        getContentPane().add(date_chooser, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 210, 160, -1));

        pack();
    }// </editor-fold>

    private void fnameActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void numberActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void submitActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        String email = mail.getText().toString();
        String stname = fname.getText().toString();
        String lastname = lname.getText().toString();
        String pnumber = number.getText().toString();
        String uname = user.getText().toString();
        String password = pword.getText().toString();
        String password2 = pword2.getText().toString();
        Date date = date_chooser.getDate();
        SimpleDateFormat DateFor = new SimpleDateFormat("yyyy/MM/dd");
        String stringDate = DateFor.format(date);
        if (terms.isSelected()) {
            if (email.equals("")) {
                JOptionPane.showMessageDialog(null, "Please enter your E-Mail.");
            } else if (stname.equals("")) {
                JOptionPane.showMessageDialog(null, "Please enter your First Name.");
            } else if (lastname.equals("")) {
                JOptionPane.showMessageDialog(null, "Please enter your Last Name.");
            } else if (pnumber.equals("")) {
                JOptionPane.showMessageDialog(null, "Please enter your Phone Number.");
            } else if (uname.equals("")) {
                JOptionPane.showMessageDialog(null, "Please enter your User Name.");
            } else if (password.equals("")) {
                JOptionPane.showMessageDialog(null, "Please enter your Password.");
            } else if (!password2.equals(password)) {
                JOptionPane.showMessageDialog(null, "Please enter your Confirm Password.");
            } else {
                try (Socket socket = new Socket("192.168.0.111", 1234)) {

                    ObjectOutputStream oos = new ObjectOutputStream(socket.getOutputStream());
                    BufferedReader in = new BufferedReader(new InputStreamReader(socket.getInputStream()));

                    String userName = null;
                    userName = uname;
                    RegisterUser regUser = new RegisterUser(userName);
                    regUser.passWord = password;
                    regUser.firstName = stname;
                    regUser.lastName = lastname;
                    regUser.email = email;
                    regUser.phone = pnumber;
                    regUser.birthDay = stringDate;

                    oos.writeObject(regUser);
                    oos.flush();
                    msg.setText(in.readLine());
                } catch (IOException e) {
                    e.printStackTrace();
                }
            }
        } else {
            msg.setText("Please accept terms and conditions to submit.");
        }

    }

    private void clearActionPerformed(java.awt.event.ActionEvent evt) {
        mail.setText(null);
        lname.setText(null);
        fname.setText(null);
        number.setText(null);
        user.setText(null);
        pword.setText(null);
        pword2.setText(null);

    }

    private void submitMouseClicked(java.awt.event.MouseEvent evt) {
        // TODO add your handling code here:
    }

    private void mailKeyReleased(java.awt.event.KeyEvent evt) {
        // TODO add your handling code here:
    }

    private void fnameKeyReleased(java.awt.event.KeyEvent evt) {
        // TODO add your handling code here:

    }

    private void mailActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegisterForm.class.getName()).log(java.util.logging.Level.SEVERE, null,
                    ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegisterForm.class.getName()).log(java.util.logging.Level.SEVERE, null,
                    ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegisterForm.class.getName()).log(java.util.logging.Level.SEVERE, null,
                    ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegisterForm.class.getName()).log(java.util.logging.Level.SEVERE, null,
                    ex);
        }
        // </editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegisterForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JButton clear;
    private javax.swing.JLabel date;
    private com.toedter.calendar.JDateChooser date_chooser;
    private javax.swing.JLabel email;
    private javax.swing.JButton exit;
    private javax.swing.JTextField fname;
    private com.toedter.calendar.JCalendar jCalendar1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lastname;
    private javax.swing.JTextField lname;
    private javax.swing.JTextField mail;
    private javax.swing.JLabel msg;
    private javax.swing.JTextField number;
    private javax.swing.JLabel password;
    private javax.swing.JLabel password2;
    private javax.swing.JLabel pnumber;
    private javax.swing.JPasswordField pword;
    private javax.swing.JPasswordField pword2;
    private javax.swing.JLabel stname;
    private javax.swing.JButton submit;
    private javax.swing.JCheckBox terms;
    private javax.swing.JLabel uname;
    private javax.swing.JTextField user;
    // End of variables declaration
}
