/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package App;

/**
 *
 * @author nrnbt
 */
public class AuctionComponent extends javax.swing.JPanel {

    /**
     * Creates new form text
     */
    public AuctionComponent() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pricePanel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        titlePanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        img = new javax.swing.JLabel();

        setBackground(new java.awt.Color(153, 153, 153));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pricePanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setText("Starting Price:");
        pricePanel.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 120, 20));

        add(pricePanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 170, 150, 20));

        titlePanel.setBackground(new java.awt.Color(255, 255, 255));
        titlePanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Created by:");
        titlePanel.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 120, 20));

        jLabel3.setText("Title:");
        titlePanel.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 100, 20));

        add(titlePanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 130, 150, 40));
        add(img, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 130, 50));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel img;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel pricePanel;
    private javax.swing.JPanel titlePanel;
    // End of variables declaration//GEN-END:variables
}
