/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Register;

import App.HomePage;
import java.awt.Color;
import java.awt.Insets;
import java.awt.Toolkit;
import java.awt.event.WindowEvent;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.*;

/**
 *
 * @author asus
 */
public class Registration extends javax.swing.JFrame {

    /**
     * Creates new form Registration
     */
    public Registration() {
        initComponents();
//        Toolkit tk = Toolkit.getDefaultToolkit();
//        int xsize = (int) tk.getScreenSize().getWidth();
//        int ysize = (int) tk.getScreenSize().getHeight();
//        Insets scnMax = Toolkit.getDefaultToolkit().getScreenInsets(getGraphicsConfiguration());
//        int taskBarSize = scnMax.bottom;
//        this.setSize(xsize,ysize - taskBarSize);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JDesktopPane = new javax.swing.JDesktopPane();
        number = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        mail = new javax.swing.JTextField();
        terms = new javax.swing.JCheckBox();
        pword = new javax.swing.JPasswordField();
        user = new javax.swing.JTextField();
        lname = new javax.swing.JTextField();
        pword2 = new javax.swing.JPasswordField();
        fname = new javax.swing.JTextField();
        emsg1 = new javax.swing.JLabel();
        emsg2 = new javax.swing.JLabel();
        emsg3 = new javax.swing.JLabel();
        emsg4 = new javax.swing.JLabel();
        emsg5 = new javax.swing.JLabel();
        emsg6 = new javax.swing.JLabel();
        emsg7 = new javax.swing.JLabel();
        esmg8 = new javax.swing.JLabel();
        kGradientPanel1 = new com.k33ptoo.components.KGradientPanel();
        kButton1 = new com.k33ptoo.components.KButton();
        kButton2 = new com.k33ptoo.components.KButton();
        msg = new javax.swing.JLabel();
        date_chooser = new com.toedter.calendar.JDateChooser();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        JDesktopPane.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        number.setForeground(new java.awt.Color(255, 255, 255));
        number.setText("Phone number");
        number.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        number.setOpaque(false);
        number.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                numberFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                numberFocusLost(evt);
            }
        });
        number.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numberActionPerformed(evt);
            }
        });
        number.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                numberKeyTyped(evt);
            }
        });
        JDesktopPane.add(number, new org.netbeans.lib.awtextra.AbsoluteConstraints(349, 218, 362, 31));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Sign Up");
        JDesktopPane.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(447, 6, 170, 60));

        mail.setForeground(new java.awt.Color(255, 255, 255));
        mail.setText("e-mail");
        mail.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        mail.setOpaque(false);
        mail.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                mailFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                mailFocusLost(evt);
            }
        });
        mail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mailActionPerformed(evt);
            }
        });
        mail.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                mailKeyReleased(evt);
            }
        });
        JDesktopPane.add(mail, new org.netbeans.lib.awtextra.AbsoluteConstraints(349, 181, 362, 31));

        terms.setBackground(new java.awt.Color(255, 204, 204));
        terms.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        terms.setForeground(new java.awt.Color(255, 255, 255));
        terms.setText("Accept terms and conditions");
        terms.setBorder(null);
        JDesktopPane.add(terms, new org.netbeans.lib.awtextra.AbsoluteConstraints(416, 365, 211, 18));

        pword.setForeground(new java.awt.Color(255, 255, 255));
        pword.setText("Password");
        pword.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        pword.setEchoChar('\u0000');
        pword.setOpaque(false);
        pword.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                pwordFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                pwordFocusLost(evt);
            }
        });
        pword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pwordActionPerformed(evt);
            }
        });
        JDesktopPane.add(pword, new org.netbeans.lib.awtextra.AbsoluteConstraints(349, 292, 362, 31));

        user.setForeground(new java.awt.Color(255, 255, 255));
        user.setText("Username");
        user.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        user.setOpaque(false);
        user.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                userFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                userFocusLost(evt);
            }
        });
        JDesktopPane.add(user, new org.netbeans.lib.awtextra.AbsoluteConstraints(349, 144, 362, 31));

        lname.setForeground(new java.awt.Color(255, 255, 255));
        lname.setText("Last name");
        lname.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        lname.setOpaque(false);
        lname.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                lnameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                lnameFocusLost(evt);
            }
        });
        lname.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                lnameKeyReleased(evt);
            }
        });
        JDesktopPane.add(lname, new org.netbeans.lib.awtextra.AbsoluteConstraints(349, 107, 362, 31));

        pword2.setForeground(new java.awt.Color(255, 255, 255));
        pword2.setText("Repeat password");
        pword2.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        pword2.setEchoChar('\u0000');
        pword2.setOpaque(false
        );
        pword2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                pword2FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                pword2FocusLost(evt);
            }
        });
        JDesktopPane.add(pword2, new org.netbeans.lib.awtextra.AbsoluteConstraints(349, 329, 362, 30));

        fname.setBackground(new Color(0,0,0,0));
        fname.setForeground(new java.awt.Color(255, 255, 255));
        fname.setText("First name");
        fname.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        fname.setOpaque(false);
        fname.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                fnameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                fnameFocusLost(evt);
            }
        });
        fname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fnameActionPerformed(evt);
            }
        });
        fname.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                fnameKeyReleased(evt);
            }
        });
        JDesktopPane.add(fname, new org.netbeans.lib.awtextra.AbsoluteConstraints(349, 70, 362, 31));

        emsg1.setForeground(new java.awt.Color(255, 255, 255));
        JDesktopPane.add(emsg1, new org.netbeans.lib.awtextra.AbsoluteConstraints(729, 70, 124, 19));

        emsg2.setForeground(new java.awt.Color(255, 255, 255));
        JDesktopPane.add(emsg2, new org.netbeans.lib.awtextra.AbsoluteConstraints(729, 107, 124, 19));

        emsg3.setForeground(new java.awt.Color(255, 255, 255));
        JDesktopPane.add(emsg3, new org.netbeans.lib.awtextra.AbsoluteConstraints(729, 144, 124, 19));

        emsg4.setForeground(new java.awt.Color(255, 255, 255));
        JDesktopPane.add(emsg4, new org.netbeans.lib.awtextra.AbsoluteConstraints(729, 181, 124, 19));

        emsg5.setForeground(new java.awt.Color(255, 255, 255));
        JDesktopPane.add(emsg5, new org.netbeans.lib.awtextra.AbsoluteConstraints(729, 218, 124, 15));

        emsg6.setForeground(new java.awt.Color(255, 255, 255));
        JDesktopPane.add(emsg6, new org.netbeans.lib.awtextra.AbsoluteConstraints(729, 255, 104, 19));

        emsg7.setForeground(new java.awt.Color(255, 255, 255));
        JDesktopPane.add(emsg7, new org.netbeans.lib.awtextra.AbsoluteConstraints(729, 292, 124, 25));

        esmg8.setForeground(new java.awt.Color(255, 255, 255));
        JDesktopPane.add(esmg8, new org.netbeans.lib.awtextra.AbsoluteConstraints(729, 339, 104, 20));

        kGradientPanel1.setkEndColor(new java.awt.Color(255, 204, 204));
        kGradientPanel1.setkStartColor(new java.awt.Color(255, 153, 255));
        kGradientPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        kButton1.setText("Submit");
        kButton1.setkBackGroundColor(new java.awt.Color(0, 0, 255));
        kButton1.setkEndColor(new java.awt.Color(51, 51, 255));
        kButton1.setkStartColor(new java.awt.Color(204, 204, 255));
        kButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kButton1ActionPerformed(evt);
            }
        });
        kGradientPanel1.add(kButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 390, 130, -1));

        kButton2.setText("Back");
        kButton2.setkBackGroundColor(new java.awt.Color(0, 0, 255));
        kButton2.setkEndColor(new java.awt.Color(102, 102, 255));
        kButton2.setkHoverEndColor(new java.awt.Color(255, 153, 153));
        kButton2.setkStartColor(new java.awt.Color(153, 153, 255));
        kButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kButton2ActionPerformed(evt);
            }
        });
        kGradientPanel1.add(kButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 390, 130, -1));

        msg.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        msg.setForeground(new java.awt.Color(255, 255, 255));
        kGradientPanel1.add(msg, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 440, 290, 30));

        date_chooser.setBackground(new java.awt.Color(255, 204, 204));
        date_chooser.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        date_chooser.setToolTipText("");
        date_chooser.setOpaque(false);
        date_chooser.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                date_chooserFocusLost(evt);
            }
        });
        kGradientPanel1.add(date_chooser, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 260, 360, 31));

        JDesktopPane.add(kGradientPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1020, 590));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JDesktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 952, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JDesktopPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        JDesktopPane.getAccessibleContext().setAccessibleName("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void fnameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_fnameKeyReleased
        // TODO add your handling code here:
        String PATTERN = "^[a-zA-Z]{0,30}$";
        Pattern patt = Pattern.compile(PATTERN);
        Matcher match=patt.matcher(fname.getText());
        if(!match.matches()){
            emsg1.setText("Invalid Username!");
        }
        else{
            emsg1.setText(null);
        }
    }//GEN-LAST:event_fnameKeyReleased

    private void fnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fnameActionPerformed

    private void fnameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_fnameFocusLost
        // TODO add your handling code here:
        if (fname.getText().equals("")){
            fname.setText("First name");
            
        }
    }//GEN-LAST:event_fnameFocusLost

    private void fnameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_fnameFocusGained
        // TODO add your handling code here:
        if (fname.getText().equals("First name")){
            fname.setText("");
            
        }
    }//GEN-LAST:event_fnameFocusGained

    private void pword2FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_pword2FocusLost
        // TODO add your handling code here:
        if (pword2.getText().equals("")){
            //pword2.setText("Repeat password");
            

        }
    }//GEN-LAST:event_pword2FocusLost

    private void pword2FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_pword2FocusGained
        // TODO add your handling code here:
        if (pword2.getText().equals("Repeat password")){
            pword2.setText("");
            
            pword2.setEchoChar('*');

        }
    }//GEN-LAST:event_pword2FocusGained

    private void lnameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_lnameKeyReleased
        // TODO add your handling code here:
        String PATTERN = "^[a-zA-Z]{0,30}$";
        Pattern patt = Pattern.compile(PATTERN);
        Matcher match=patt.matcher(lname.getText());
        if(!match.matches()){
            emsg2.setText("Invalid Lastname!");
        }
        else{
            emsg2.setText(null);
        }
    }//GEN-LAST:event_lnameKeyReleased

    private void lnameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_lnameFocusLost
        // TODO add your handling code here:
        if (lname.getText().equals("")){
            lname.setText("Last name");
            
        }
    }//GEN-LAST:event_lnameFocusLost

    private void lnameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_lnameFocusGained
        // TODO add your handling code here:
        if (lname.getText().equals("Last name")){
            lname.setText("");
            
        }
    }//GEN-LAST:event_lnameFocusGained

    private void userFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_userFocusLost
        // TODO add your handling code here:
        if (user.getText().equals("")){
            user.setText("Username");
            
        }
    }//GEN-LAST:event_userFocusLost

    private void userFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_userFocusGained
        // TODO add your handling code here:
        if (user.getText().equals("Username")){
            user.setText("");
           
        }
    }//GEN-LAST:event_userFocusGained

    private void pwordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pwordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pwordActionPerformed

    private void pwordFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_pwordFocusLost
        // TODO add your handling code here:
        if (pword.getText().equals("")){
            //pword.setText("Password");
            

        }
    }//GEN-LAST:event_pwordFocusLost

    private void pwordFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_pwordFocusGained
        // TODO add your handling code here:
        if (pword.getText().equals("Password")){
            pword.setText("");
           
            pword.setEchoChar('*');
        }
    }//GEN-LAST:event_pwordFocusGained

    private void date_chooserFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_date_chooserFocusLost
        // TODO add your handling code here:

    }//GEN-LAST:event_date_chooserFocusLost

    private void mailKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_mailKeyReleased
        // TODO add your handling code here:
        String PATTERN = "^[a-zA-Z0-9]{0,30}[@][a-zA-Z0-9]{0,10}[.][a-zA-Z]{0,5}$";
        Pattern patt = Pattern.compile(PATTERN);
        Matcher match=patt.matcher(mail.getText());
        if(!match.matches()){
            emsg4.setText("Email is incorrect!");
        }
        else{
            emsg4.setText(null);
        }
    }//GEN-LAST:event_mailKeyReleased

    private void mailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mailActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_mailActionPerformed

    private void mailFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_mailFocusLost
        // TODO add your handling code here:
        if (mail.getText().equals("")){
            mail.setText("e-mail");
            
        }
    }//GEN-LAST:event_mailFocusLost

    private void mailFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_mailFocusGained
        // TODO add your handling code here:
        if (mail.getText().equals("e-mail")){
            mail.setText("");
            
        }
    }//GEN-LAST:event_mailFocusGained

    private void numberKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_numberKeyTyped
        // TODO add your handling code here:
        if (!Character.isDigit(evt.getKeyChar())){
            evt.consume();
        }
    }//GEN-LAST:event_numberKeyTyped

    private void numberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_numberActionPerformed

    private void numberFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_numberFocusLost
        // TODO add your handling code here:
        if (number.getText().equals("")){
            number.setText("Phone number");
            
        }
    }//GEN-LAST:event_numberFocusLost

    private void numberFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_numberFocusGained
        // TODO add your handling code here:
        if (number.getText().equals("Phone number")){
            number.setText("");
            
        }
    }//GEN-LAST:event_numberFocusGained

    private void kButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kButton1ActionPerformed
        // TODO add your handling code here
         String email = mail.getText().toString();
        System.out.println(email);
        String stname = fname.getText().toString();
        System.out.println(stname);
        String lastname = lname.getText().toString();
        System.out.println(lastname);
        String pnumber = number.getText().toString();
        System.out.println(pnumber);
        String uname = user.getText().toString();
        System.out.println(uname);
        String password = pword.getText().toString();
        System.out.println(password);
        String password2 = pword2.getText().toString();
        System.out.println(password2);
        Date date = date_chooser.getDate();
        SimpleDateFormat DateFor = new SimpleDateFormat("yyyy/MM/dd");
        String stringDate = DateFor.format(date);
        System.out.println(stringDate);
        if (email.equals("")) {
            JOptionPane.showMessageDialog(null, "Please enter your E-Mail.");
        }
        if (email.equals("e-mail")) {
            JOptionPane.showMessageDialog(null, "Please enter your E-Mail.");
        }
        if (stname.equals("")) {
            JOptionPane.showMessageDialog(null, "Please enter your First Name.");
        }
        if (stname.equals("First name")) {
            JOptionPane.showMessageDialog(null, "Please enter your First Name.");
        }
        if (lastname.equals("")) {
            JOptionPane.showMessageDialog(null, "Please enter your Last Name.");
        }
        if (lastname.equals("Last name")) {
            JOptionPane.showMessageDialog(null, "Please enter your Last Name.");
        }
        if (pnumber.equals("")) {
            JOptionPane.showMessageDialog(null, "Please enter your Phone Number.");
        }
        if (pnumber.equals("Phone number")) {
            JOptionPane.showMessageDialog(null, "Please enter your Phone Number.");
        }
        if (uname.equals("")) {
            JOptionPane.showMessageDialog(null, "Please enter your User Name.");
        }
        if (uname.equals("Username")) {
            JOptionPane.showMessageDialog(null, "Please enter your User Name.");
        }
        if (password.equals("")) {
            JOptionPane.showMessageDialog(null, "Please enter your Password.");
        }
        if (password.equals("password")) {
            JOptionPane.showMessageDialog(null, "Please enter your Password.");
        }
        if (password2.equals("")) {
            JOptionPane.showMessageDialog(null, "Please enter your Confirm Password.");
        }
        if (password2.equals("Repeat password")) {
            JOptionPane.showMessageDialog(null, "Please repeat your Password.");
        }
        if (password.equals(password2)== false)
        {
            JOptionPane.showMessageDialog(null,"Password Doesn't Match");
        }
        if (terms.isSelected()) {
            msg.setText("Registration Successfull");
        } else {
            msg.setText("Please accept terms and conditions to submit.");
        }
    }//GEN-LAST:event_kButton1ActionPerformed

    private void kButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kButton2ActionPerformed
        // TODO add your handling code here:
         this.hide();
       HomePage frm = new HomePage();
               frm.setVisible(true);
    }//GEN-LAST:event_kButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
           UIManager.setLookAndFeel("com.jtattoo.plaf.mcwin.McWinLookAndFeel");
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Registration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Registration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Registration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Registration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Registration().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane JDesktopPane;
    private com.toedter.calendar.JDateChooser date_chooser;
    private javax.swing.JLabel emsg1;
    private javax.swing.JLabel emsg2;
    private javax.swing.JLabel emsg3;
    private javax.swing.JLabel emsg4;
    private javax.swing.JLabel emsg5;
    private javax.swing.JLabel emsg6;
    private javax.swing.JLabel emsg7;
    private javax.swing.JLabel esmg8;
    private javax.swing.JTextField fname;
    private javax.swing.JLabel jLabel2;
    private com.k33ptoo.components.KButton kButton1;
    private com.k33ptoo.components.KButton kButton2;
    private com.k33ptoo.components.KGradientPanel kGradientPanel1;
    private javax.swing.JTextField lname;
    private javax.swing.JTextField mail;
    private javax.swing.JLabel msg;
    private javax.swing.JTextField number;
    private javax.swing.JPasswordField pword;
    private javax.swing.JPasswordField pword2;
    private javax.swing.JCheckBox terms;
    private javax.swing.JTextField user;
    // End of variables declaration//GEN-END:variables
}
